// Code generated by fixture. DO NOT EDIT.

package shimsgeneratedincluded

import "strings"

func Trim(value string) string { // want "avoid a trivial forwarding function"
	return strings.TrimSpace(value)
}
